import type { AppRouteRecordRaw } from '../types/router'

/**
 * Định nghĩa tất cả routes của admin.
 * Menu đa cấp được cấu hình trong src/config/sidebar-menu.ts
 */
export const routes: AppRouteRecordRaw[] = [
  {
    path: '/',
    name: 'Root',
    redirect: { name: 'Dashboard' },
    meta: { title: 'nav.home', hideInSidebar: true },
  },
  {
    path: '/dashboard',
    name: 'Dashboard',
    component: () => import('../views/DashboardView.vue'),
    meta: { title: 'nav.dashboard', icon: 'bi-speedometer2', order: 1 },
  },
  {
    path: '/users',
    name: 'Users',
    component: () => import('../views/UsersView.vue'),
    meta: { title: 'nav.userManagement', icon: 'bi-people', order: 2 },
  },
  {
    path: '/products',
    name: 'ProductList',
    component: () => import('../views/products/ProductListView.vue'),
    meta: { title: 'nav.productList', icon: 'bi-box-seam', order: 3 },
  },
  {
    path: '/products/:id',
    name: 'ProductDetail',
    component: () => import('../views/products/ProductDetailView.vue'),
    meta: { title: 'nav.productDetail', hideInSidebar: true },
  },
  {
    path: '/products/add',
    name: 'ProductAdd',
    component: () => import('../views/products/ProductAddView.vue'),
    meta: { title: 'nav.addProduct', hideInSidebar: true },
  },
  {
    path: '/products/categories',
    name: 'ProductCategories',
    component: () => import('../views/products/ProductCategoriesView.vue'),
    meta: { title: 'nav.productCategories', icon: 'bi-tags', order: 3 },
  },
  {
    path: '/orders',
    name: 'OrderList',
    component: () => import('../views/orders/OrderListView.vue'),
    meta: { title: 'nav.orderList', icon: 'bi-cart-check', order: 4 },
  },
  {
    path: '/orders/:id',
    name: 'OrderDetail',
    component: () => import('../views/orders/OrderDetailView.vue'),
    meta: { title: 'nav.orderDetail', hideInSidebar: true },
  },
  {
    path: '/orders/create',
    name: 'OrderCreate',
    component: () => import('../views/orders/OrderCreateView.vue'),
    meta: { title: 'nav.createOrder', hideInSidebar: true },
  },
  {
    path: '/drive',
    name: 'Drive',
    component: () => import('../views/drive/DriveView.vue'),
    meta: { title: 'nav.myDrive', icon: 'bi-cloud-arrow-up', order: 4.5 },
  },
  {
    path: '/messenger',
    name: 'Messenger',
    component: () => import('../views/messenger/MessengerView.vue'),
    meta: { title: 'nav.messenger', icon: 'bi-chat-dots', order: 4.6 },
  },
  {
    path: '/reports/sales',
    name: 'ReportSales',
    component: () => import('../views/reports/ReportSalesView.vue'),
    meta: { title: 'nav.salesReport', icon: 'bi-graph-up', order: 5 },
  },
  {
    path: '/reports/users',
    name: 'ReportUsers',
    component: () => import('../views/reports/ReportUsersView.vue'),
    meta: { title: 'nav.userReport', icon: 'bi-people', order: 5 },
  },
  {
    path: '/reports/attendance',
    name: 'ReportAttendance',
    component: () => import('../views/reports/ReportAttendanceView.vue'),
    meta: { title: 'nav.reportAttendance', hideInSidebar: true },
  },
  {
    path: '/reports/payroll',
    name: 'ReportPayroll',
    component: () => import('../views/reports/ReportPayrollView.vue'),
    meta: { title: 'nav.reportPayroll', hideInSidebar: true },
  },
  {
    path: '/reports/inventory',
    name: 'ReportInventory',
    component: () => import('../views/reports/ReportInventoryView.vue'),
    meta: { title: 'nav.reportInventory', hideInSidebar: true },
  },
  {
    path: '/reports/receivables',
    name: 'ReportReceivables',
    component: () => import('../views/reports/ReportReceivablesView.vue'),
    meta: { title: 'nav.reportReceivables', hideInSidebar: true },
  },
  // Tài sản
  {
    path: '/assets',
    name: 'AssetsOverview',
    component: () => import('../views/assets/AssetsOverviewView.vue'),
    meta: { title: 'nav.assetsOverview', icon: 'bi-building', order: 5.5 },
  },
  {
    path: '/assets/list',
    name: 'AssetsList',
    component: () => import('../views/assets/AssetsListView.vue'),
    meta: { title: 'nav.assetsList', hideInSidebar: true },
  },
  {
    path: '/assets/depreciation',
    name: 'Depreciation',
    component: () => import('../views/assets/DepreciationView.vue'),
    meta: { title: 'nav.depreciation', hideInSidebar: true },
  },
  {
    path: '/assets/maintenance',
    name: 'Maintenance',
    component: () => import('../views/assets/MaintenanceView.vue'),
    meta: { title: 'nav.maintenance', hideInSidebar: true },
  },
  {
    path: '/assets/types',
    name: 'AssetTypes',
    component: () => import('../views/assets/AssetTypesView.vue'),
    meta: { title: 'nav.assetTypes', hideInSidebar: true },
  },
  // Kho hàng
  {
    path: '/warehouse',
    name: 'WarehouseOverview',
    component: () => import('../views/warehouse/WarehouseOverviewView.vue'),
    meta: { title: 'nav.warehouseOverview', icon: 'bi-boxes', order: 5.6 },
  },
  {
    path: '/warehouse/list',
    name: 'WarehousesList',
    component: () => import('../views/warehouse/WarehousesListView.vue'),
    meta: { title: 'nav.warehousesList', hideInSidebar: true },
  },
  {
    path: '/warehouse/stock-in',
    name: 'StockIn',
    component: () => import('../views/warehouse/StockInView.vue'),
    meta: { title: 'nav.stockIn', hideInSidebar: true },
  },
  {
    path: '/warehouse/stock-out',
    name: 'StockOut',
    component: () => import('../views/warehouse/StockOutView.vue'),
    meta: { title: 'nav.stockOut', hideInSidebar: true },
  },
  {
    path: '/warehouse/stocktake',
    name: 'Stocktake',
    component: () => import('../views/warehouse/StocktakeView.vue'),
    meta: { title: 'nav.stocktake', hideInSidebar: true },
  },
  {
    path: '/warehouse/stock-level',
    name: 'StockLevel',
    component: () => import('../views/warehouse/StockLevelView.vue'),
    meta: { title: 'nav.stockLevel', hideInSidebar: true },
  },
  // Kế toán
  {
    path: '/accounting',
    name: 'AccountingDashboard',
    component: () => import('../views/accounting/AccountingDashboardView.vue'),
    meta: { title: 'nav.accountingOverview', icon: 'bi-calculator', order: 6 },
  },
  {
    path: '/accounting/invoices',
    name: 'Invoices',
    component: () => import('../views/accounting/InvoicesView.vue'),
    meta: { title: 'nav.invoices', hideInSidebar: true },
  },
  {
    path: '/accounting/receipts',
    name: 'Receipts',
    component: () => import('../views/accounting/ReceiptsView.vue'),
    meta: { title: 'nav.receipts', hideInSidebar: true },
  },
  {
    path: '/accounting/payments',
    name: 'Payments',
    component: () => import('../views/accounting/PaymentsView.vue'),
    meta: { title: 'nav.payments', hideInSidebar: true },
  },
  {
    path: '/accounting/receivables',
    name: 'Receivables',
    component: () => import('../views/accounting/ReceivablesView.vue'),
    meta: { title: 'nav.receivables', hideInSidebar: true },
  },
  {
    path: '/accounting/financial-reports',
    name: 'FinancialReports',
    component: () => import('../views/accounting/FinancialReportsView.vue'),
    meta: { title: 'nav.financialReports', hideInSidebar: true },
  },
  {
    path: '/accounting/tax',
    name: 'Tax',
    component: () => import('../views/accounting/TaxView.vue'),
    meta: { title: 'nav.tax', hideInSidebar: true },
  },
  {
    path: '/accounting/budget',
    name: 'Budget',
    component: () => import('../views/accounting/BudgetView.vue'),
    meta: { title: 'nav.budget', hideInSidebar: true },
  },
  // Nhân sự
  {
    path: '/hr',
    name: 'HRDashboard',
    component: () => import('../views/hr/HRDashboardView.vue'),
    meta: { title: 'nav.hrOverview', icon: 'bi-person-badge', order: 7 },
  },
  {
    path: '/hr/employees',
    name: 'Employees',
    component: () => import('../views/hr/EmployeesView.vue'),
    meta: { title: 'nav.employees', hideInSidebar: true },
  },
  {
    path: '/hr/attendance',
    name: 'Attendance',
    component: () => import('../views/hr/AttendanceView.vue'),
    meta: { title: 'nav.attendance', hideInSidebar: true },
  },
  {
    path: '/hr/payroll',
    name: 'Payroll',
    component: () => import('../views/hr/PayrollView.vue'),
    meta: { title: 'nav.payroll', hideInSidebar: true },
  },
  {
    path: '/hr/contracts',
    name: 'Contracts',
    component: () => import('../views/hr/ContractsView.vue'),
    meta: { title: 'nav.contracts', hideInSidebar: true },
  },
  {
    path: '/hr/training',
    name: 'Training',
    component: () => import('../views/hr/TrainingView.vue'),
    meta: { title: 'nav.training', hideInSidebar: true },
  },
  {
    path: '/hr/recruitment',
    name: 'Recruitment',
    component: () => import('../views/hr/RecruitmentView.vue'),
    meta: { title: 'nav.recruitment', hideInSidebar: true },
  },
  {
    path: '/hr/departments',
    name: 'Departments',
    component: () => import('../views/hr/DepartmentsView.vue'),
    meta: { title: 'nav.departments', hideInSidebar: true },
  },
  {
    path: '/hr/shifts',
    name: 'Shifts',
    component: () => import('../views/hr/ShiftsView.vue'),
    meta: { title: 'nav.shifts', hideInSidebar: true },
  },
  {
    path: '/hr/leave',
    name: 'Leave',
    component: () => import('../views/hr/LeaveView.vue'),
    meta: { title: 'nav.leave', hideInSidebar: true },
  },
  {
    path: '/hr/payslips',
    name: 'Payslips',
    component: () => import('../views/hr/PayslipsView.vue'),
    meta: { title: 'nav.payslips', hideInSidebar: true },
  },
  {
    path: '/settings',
    name: 'Settings',
    component: () => import('../views/SettingsView.vue'),
    meta: { title: 'nav.generalSettings', icon: 'bi-gear', order: 10 },
  },
  {
    path: '/settings/system',
    name: 'SettingsSystem',
    component: () => import('../views/settings/SettingsSystemView.vue'),
    meta: { title: 'nav.systemSettings', hideInSidebar: true },
  },
  {
    path: '/settings/themes',
    name: 'SettingsThemes',
    component: () => import('../views/settings/SettingsThemesView.vue'),
    meta: { title: 'nav.themes', hideInSidebar: true },
  },
  {
    path: '/demo/buttons',
    name: 'DemoButtons',
    component: () => import('../views/demo/DemoButtonsView.vue'),
    meta: { title: 'nav.demoButtons', icon: 'bi-hand-index-thumb', order: 9 },
  },
  {
    path: '/demo/alerts',
    name: 'DemoAlerts',
    component: () => import('../views/demo/DemoAlertsView.vue'),
    meta: { title: 'nav.demoAlerts', icon: 'bi-exclamation-triangle', order: 9 },
  },
  {
    path: '/demo/cards',
    name: 'DemoCards',
    component: () => import('../views/demo/DemoCardsView.vue'),
    meta: { title: 'nav.demoCards', icon: 'bi-card-text', order: 9 },
  },
  {
    path: '/demo/forms',
    name: 'DemoForms',
    component: () => import('../views/demo/DemoFormsView.vue'),
    meta: { title: 'nav.demoForms', icon: 'bi-input-cursor-text', order: 9 },
  },
  {
    path: '/demo/badges',
    name: 'DemoBadges',
    component: () => import('../views/demo/DemoBadgesView.vue'),
    meta: { title: 'nav.demoBadges', icon: 'bi-tag', order: 9 },
  },
  {
    path: '/demo/progress',
    name: 'DemoProgress',
    component: () => import('../views/demo/DemoProgressView.vue'),
    meta: { title: 'nav.demoProgress', icon: 'bi-bar-chart', order: 9 },
  },
  {
    path: '/demo/tables',
    name: 'DemoTables',
    component: () => import('../views/demo/DemoTablesView.vue'),
    meta: { title: 'nav.demoTables', icon: 'bi-table', order: 9 },
  },
  {
    path: '/demo/dropdowns',
    name: 'DemoDropdowns',
    component: () => import('../views/demo/DemoDropdownsView.vue'),
    meta: { title: 'nav.demoDropdowns', icon: 'bi-menu-button', order: 9 },
  },
  {
    path: '/demo/nav-tabs',
    name: 'DemoNavTabs',
    component: () => import('../views/demo/DemoNavTabsView.vue'),
    meta: { title: 'nav.demoNavTabs', icon: 'bi-tabs', order: 9 },
  },
  {
    path: '/demo/spinners',
    name: 'DemoSpinners',
    component: () => import('../views/demo/DemoSpinnersView.vue'),
    meta: { title: 'nav.demoSpinners', icon: 'bi-arrow-repeat', order: 9 },
  },
  {
    path: '/demo/typography',
    name: 'DemoTypography',
    component: () => import('../views/demo/DemoTypographyView.vue'),
    meta: { title: 'nav.demoTypography', icon: 'bi-type', order: 9 },
  },
  {
    path: '/demo/utilities',
    name: 'DemoUtilities',
    component: () => import('../views/demo/DemoUtilitiesView.vue'),
    meta: { title: 'nav.demoUtilities', icon: 'bi-brush', order: 9 },
  },
  {
    path: '/demo/components',
    name: 'ComponentsDemo',
    component: () => import('../views/demo/ComponentsDemoView.vue'),
    meta: { title: 'nav.demoComponents', icon: 'bi-puzzle', order: 9 },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('../views/NotFoundView.vue'),
    meta: { title: 'nav.notFound', hideInSidebar: true },
  },
]
